### ISSUE TITLE
How to use IntrospectionQuery to compile a schema?

### ISSUE THREAD

**Issue by lvarayut** [arangodb/graphql-sync#2]
Would it be possible to generate a `schema.json` using GraphQL introspection with `graphql-sync`? I'm using Relay in the front-end and it requires the `schema.json` which is the compiled version of the `schema.js`. So, if I defined the `schema.js` in a Foxx service, using this plugin,I had to compile it to `schema.json` and somehow pass it to the front-end.

For example,

```js
import { graphql } from 'graphql-sync';
import { introspectionQuery } from 'graphql/utilities';
import schema from './schema';
...
   // Not sure how to do the following line using graphql-sync
   let json = await graphql(schema, introspectionQuery);
...
```

**Comment by pluma** [comment]
I've answered this in the comments of the article:
https://www.arangodb.com/2016/02/using-graphql-nosql-database-arangodb/#comment-2545199830

> The schema.json Relay wants is just the output of this:
>
> ```js
> const util = require('graphql/utilities');
> const schemaDotJson = util.printSchema(graphql(Schema, util.introspectionQuery));
> ```
>
> graphql-sync doesn't currently have the utilities sub-module but you should be able to just install graphql-js alongside it and use the utilities from there (and the graphql function from graphql-sync).
>
> graphql-sync is fully compatible with graphql-js, it just provides a copy of the outer most layer of the main API that removes the promise logic.

I'll add the utilities submodule to this module and make sure it behaves the same.

**Comment by lvarayut** [comment]
Thanks for your response. After compilation, how do you pass the compiled scheme.json to the front-end. The only way I can think of is to create a simple api, for example, /get-schema in the Foxx service. Then, tell the front-end to make a GET request to it. Any suggestion would be appreciated.

**Comment by pluma** [comment]
That would be the most straightforward solution.

You could have two endpoints: `POST /graphql` for the GraphQL endpoint and `GET /schema` (or `GET /graphql/schema` -- or even `GET /graphql`) for the schema.

**Comment by lvarayut** [comment]
Thanks @pluma. I'll give it a try.

**Comment by pluma** [comment]
Fixed in the new release. graphql-sync now exports all functions exported by graphql-js, so you can just use `require('graphql-sync').introspectionQuery` directly.
