### ISSUE TITLE
New version doesn't yield error

### ISSUE THREAD

**Issue by mariusrak** [arangodb/graphql-sync#3]
I tried to use newst version of this wrapper "0.5.0-sync.1" but It didn't work at all. I only got json with single member "errors" which was empty array. When i copied module from foxx example graphql app, I finally got some useful output: 

`{ "errors" : [ [Object { "message" : "Syntax Error GraphQL request (1:2) Expected Name, found String \"query\"\n\n1: {\"query\":\"query Main {\\n  User {\\n    ...F0\\n  }\\n}\\nfragment F0 on User {\\n  name,\\n  email\\n}\",\"variables\":{}}\n    ^\n" }] ] }`

Also, it seems that in newest version `gql.graphql(schema, query);`returns promise instead of actual result.

**Comment by pluma** [comment]
Gotcha. I was checking against the demo app, which actually bundles a different version than the package.json indicates.

**Comment by pluma** [comment]
@mariusrak the only problem seems to have been the index.js's exports. It accidentally overwrote the exports of graphql-sync with those of graphql-js instead of merely adding to them. Object spread expressions are hard, I guess.

**Comment by pluma** [comment]
I've also updated the demo-graphql service so you can try it out.

**Comment by mariusrak** [comment]
Nope, update didn't help with the error. There is still no message in errors. 
Problem in my code is when I do this: `gql.graphql(schema, req.body());` When I do `gql.graphql(schema, req.body().query);` It works. 

But it seems that You solve the problem with promise :)

**Comment by pluma** [comment]
Ah, the problem seems to be that the errors are actual `Error` objects, which don't get serialized properly.

**Comment by pluma** [comment]
I've updated the demo service to correctly use graphql's `formatError` function to output the errors for JSON. Error objects are not serializable because all the interesting properties are non-enumerable, resulting in an empty object in JSON. The `formatError` method provided by graphql-sync (from graphql-js) converts the Error objects to plain objects with the relevant (enumerable) properties for JSON.

As for your problem: the GraphQL endpoint should accept request bodies in the GraphQL format, not JSON objects. You have to use `req.rawBody()` to get the plain text request body (`req.body()` parses it as JSON). Take a closer look at the controller from the demo service: https://github.com/arangodb-foxx/demo-graphql/blob/master/controller.js

**Comment by mariusrak** [comment]
Yes, first time I used it as `gql.graphql(schema, req.rawBody());` but I got error I mentioned in first post. When I parsed JSON from request, and used just `query` member from the JSON everything works correctly. It's because I use relay which besides query also sends variables, so I need to pass only query to gql engine.

**Comment by agungsb** [comment]
Hi @mariusrak , I am facing the issue right now. I need help. I'm using Relay for the frontend and Foxx for backend. I keep getting the error which is similar with the error you got:

`Syntax Error GraphQL request (1:2) Expected Name, found String \"query\"\n\n1: {\"query\":\"\\n  query IntrospectionQuery {\\n    __schema {\\n      queryType { name }\\n      mutationType { name }\\n      types {\\n        ...FullType\\n      }\\n      directives {\\n        name\\n        description\\n        args {\\n          ...InputValue\\n        }\\n        onOperation\\n        onFragment\\n        onField\\n      }\\n    }\\n  }\\n\\n  fragment FullType on __Type {\\n    kind\\n    name\\n    description\\n    fields {\\n      name\\n      description\\n      args {\\n        ...InputValue\\n      }\\n      type {\\n        ...TypeRef\\n      }\\n      isDeprecated\\n      deprecationReason\\n    }\\n    inputFields {\\n      ...InputValue\\n    }\\n    interfaces {\\n      ...TypeRef\\n    }\\n    enumValues {\\n      name\\n      description\\n      isDeprecated\\n      deprecationReason\\n    }\\n    possibleTypes {\\n      ...TypeRef\\n    }\\n  }\\n\\n  fragment InputValue on __InputValue {\\n    name\\n    description\\n    type { ...TypeRef }\\n    defaultValue\\n  }\\n\\n  fragment TypeRef on __Type {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n        }\\n      }\\n    }\\n  }\\n\",\"variables\":null}\n    ^\n`

Here are pieces of my Foxx codes:

```
ctrl.post('/graphql', function (req, res) {
  // By just passing the raw body string to graphql
  // we let the GraphQL library take care of making
  // sure the query is well-formed and valid.
  // Our HTTP API doesn't have to know anything about
  // GraphQL to handle it.
  const result = graphql(schema, req.rawBody(), null, req.parameters);
  if (result.errors) {
    res.status(400);
    res.json({
      errors: result.errors.map(function (error) {
        return formatError(error);
      })
    });
  } else {	
    res.json(result);
  }
})
```

You said that:

> When I parsed JSON from request, and used just query member from the JSON everything works correctly.

Would you please tell me how to achieve it using my code? Thanks.

**Comment by mariusrak** [comment]
I belive You have to use `req.body()` instead of `req.rawBody()` in spite of what pluma says. At leas it helped me. However, I'm not sure how stuf works around that so be careful. If you find some further info about this, please let me know.

**Comment by pluma** [comment]
No, rawBody is correct. In ArangoDB 2.8 (or 3.0 legacy mode) the `body` method always attempts to parse the body as JSON. GraphQL queries are not JSON even if GraphQL and JSON look superficially similar. See the GraphQL demo service (which works fine): https://github.com/arangodb-foxx/demo-graphql/blob/v1.2.1/controller.js#L16

However **Relay** is built on top of GraphQL and seems to be passing more than the raw GraphQL query to the endpoint and indeed wraps the query as a JSON string in a JSON object. So if you are trying to make graphql-sync work with Relay inside Foxx you need to parse the body as JSON and only pass the actual GraphQL query to Foxx. I suggest simply looking at the actual request body Relay sends to the server (either via the network inspector in the browser or by logging out the raw request body in Foxx before handling it) to learn more about how Relay wraps the query.

**Comment by agungsb** [comment]
I managed to solve the problem by parse req.rawBody() and use its query property. 

const result = graphql(schema, JSON.parse(req.rawBody()).query, null, req.parameters);

**Comment by pluma** [comment]
@agungsb for 2.8 you should be able to simply use `req.body()` instead of `JSON.parse(req.rawBody())`. `rawBody` is a string, `body` is the string parsed as JSON (unless you define a request body schema/model).

**Comment by mariusrak** [comment]
pluma, but the GraphQL engine requires just the .query part of whole body. There are some more fields in json which will cause problem. Therefore body has to be parsed as json. So @agungsb is doing it right. I don't think GraphQL query would be parse as json even though it's similiar structure with json.

**Comment by pluma** [comment]
@mariusrak the result of `req.body` is just an object. You can still do `req.body().query` instead of `JSON.parse(req.rawBody()).query`. I'm just arguing that there is no need to do the JSON parsing yourself.

**Comment by agungsb** [comment]
Hi, @pluma, for your information, I use ArangoDB 3.0.0. Thanks for the suggestion anyway. You're right. I could just use req.body().query instead of parse req.rawBody() to JSON. 

To be honest, I'm a little bit confused by req.rawBody(). If I use it like the following,

```
const result = graphql(schema, req.rawBody(), null, req.parameters);
```

it doesn't work and displays error as above instead. 

**But** if I assign the value of req.rawBody() to a static string variable as the following:

```
// req.rawBody()'s value is "query ViewerQuery {\r\n  viewer {\r\n    ...F0\r\n  }\r\n}\r\nfragment F0 on Root {\r\n  _hero1wKRDW:hero(episode:\"Awakens\") {\r\n    name,\r\n    species,\r\n    appearsIn {\r\n      title,\r\n      description,\r\n      __typename\r\n    },\r\n    id,\r\n    __typename\r\n  }\r\n}"

const query = "query ViewerQuery {\r\n  viewer {\r\n    ...F0\r\n  }\r\n}\r\nfragment F0 on Root {\r\n  _hero1wKRDW:hero(episode:\"Awakens\") {\r\n    name,\r\n    species,\r\n    appearsIn {\r\n      title,\r\n      description,\r\n      __typename\r\n    },\r\n    id,\r\n    __typename\r\n  }\r\n}";
const result = graphql(schema, query, null, req.parameters);
```

it works without error.

Shouldn't req.rawBody() working too since it's also a string?

**Comment by pluma** [comment]
@agungsb I'm assuming you're not using the legacy compatibility mode for 2.8 services and instead using the new Foxx API (i.e. you use "routers" not "controllers").

In this case the two properties are called `req.body` and `req.rawBody` and they're not methods (they are just regular properties and already contain the values).

In Foxx 3.0 the `rawBody` property is the equivalent to 2.8's `rawBodyBuffer()` method. So it contains a buffer, not a string. The `body` property on the other hand now contains a string (unless you explicitly define a request body).

So to clarify:

1. If you are using ArangoDB 2.8 or a service written for 2.8 running in ArangoDB 3.0's compatibility mode:
  1. If you are using Relay, use `req.body().query`.
  2. If you are using plain GraphQL, use `req.rawBody()`.
2. If you are using ArangoDB 3.0 with the new Foxx API:
  1. If you are using Relay, use `req.body.query` and make sure to add request body definition like `.body(joi.object().required())` to your endpoint.
  2. If you are using plain GraphQL, use `req.body` and make sure NOT to add a request body definition to your endpoint.

Cheers.

**Comment by agungsb** [comment]
Thanks @mariusrak and @pluma for helping me to solve my problem.

:)
